[2024-07-25T23:29:44.223+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T23:29:44.351+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.md_exchange_rate_d manual__2024-07-25T23:29:22.087413+00:00 [queued]>
[2024-07-25T23:29:44.418+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.md_exchange_rate_d manual__2024-07-25T23:29:22.087413+00:00 [queued]>
[2024-07-25T23:29:44.422+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-07-25T23:29:44.511+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): md_exchange_rate_d> on 2024-07-25 23:29:22.087413+00:00
[2024-07-25T23:29:44.655+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=72) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-25T23:29:44.681+0000] {standard_task_runner.py:64} INFO - Started process 92 to run task
[2024-07-25T23:29:44.689+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'md_exchange_rate_d', 'manual__2024-07-25T23:29:22.087413+00:00', '--job-id', '402', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmp5xbsx_34']
[2024-07-25T23:29:44.700+0000] {standard_task_runner.py:91} INFO - Job 402: Subtask md_exchange_rate_d
[2024-07-25T23:29:45.960+0000] {task_command.py:426} INFO - Running <TaskInstance: insert_data.md_exchange_rate_d manual__2024-07-25T23:29:22.087413+00:00 [running]> on host 04b0ec8dd5cd
[2024-07-25T23:29:46.676+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sfakhrutdinov' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='md_exchange_rate_d' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T23:29:22.087413+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-25T23:29:22.087413+00:00'
[2024-07-25T23:29:46.693+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T23:29:46.936+0000] {base.py:84} INFO - Using connection ID 'postgres-db' for task execution.
[2024-07-25T23:29:47.607+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-25T23:29:47.663+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T23:29:47.753+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=md_exchange_rate_d, run_id=manual__2024-07-25T23:29:22.087413+00:00, execution_date=20240725T232922, start_date=20240725T232944, end_date=20240725T232947
[2024-07-25T23:29:47.926+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-25T23:29:48.031+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
