[2024-07-19T13:37:31.777+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-19T13:37:31.960+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.ft_posting_f manual__2024-07-19T13:37:20.874860+00:00 [queued]>
[2024-07-19T13:37:31.997+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.ft_posting_f manual__2024-07-19T13:37:20.874860+00:00 [queued]>
[2024-07-19T13:37:32.001+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-07-19T13:37:32.076+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): ft_posting_f> on 2024-07-19 13:37:20.874860+00:00
[2024-07-19T13:37:32.125+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=136) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-19T13:37:32.140+0000] {standard_task_runner.py:64} INFO - Started process 149 to run task
[2024-07-19T13:37:32.160+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'ft_posting_f', 'manual__2024-07-19T13:37:20.874860+00:00', '--job-id', '339', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpdhp1aa0w']
[2024-07-19T13:37:32.169+0000] {standard_task_runner.py:91} INFO - Job 339: Subtask ft_posting_f
[2024-07-19T13:37:32.392+0000] {task_command.py:426} INFO - Running <TaskInstance: insert_data.ft_posting_f manual__2024-07-19T13:37:20.874860+00:00 [running]> on host 04b0ec8dd5cd
[2024-07-19T13:37:32.583+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sfakhrutdinov' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='ft_posting_f' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T13:37:20.874860+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-19T13:37:20.874860+00:00'
[2024-07-19T13:37:32.588+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-19T13:37:32.702+0000] {base.py:84} INFO - Using connection ID 'postgres-db' for task execution.
[2024-07-19T13:37:34.463+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-19T13:37:34.466+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-19T13:37:34.476+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=ft_posting_f, run_id=manual__2024-07-19T13:37:20.874860+00:00, execution_date=20240719T133720, start_date=20240719T133731, end_date=20240719T133734
[2024-07-19T13:37:34.560+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-19T13:37:34.606+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-19T13:37:34.607+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
